"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.parser = exports.renderingManager = exports.variantRegistry = exports.rendererRegistry = exports.htmlViewModel = void 0;
const parser_1 = require("./parser/parser");
const default_renderer_1 = require("./rendering/default-renderer");
const renderer_registry_1 = require("./rendering/renderer-registry");
const rendering_manager_1 = require("./rendering/rendering-manager");
const variant_registry_1 = require("./rendering/variant-registry");
var html_view_1 = require("./html-view");
Object.defineProperty(exports, "htmlViewModel", { enumerable: true, get: function () { return html_view_1.htmlViewModel; } });
const defaultRenderer = new default_renderer_1.DefaultRenderer();
exports.rendererRegistry = new renderer_registry_1.RendererRegistry(defaultRenderer);
exports.variantRegistry = new variant_registry_1.VariantRegistry();
exports.renderingManager = new rendering_manager_1.RenderingManager(exports.rendererRegistry, exports.variantRegistry);
exports.parser = new parser_1.Parser();
