name: Test

on: [push, pull_request]

jobs:

  Specs:
    name: Atom Specs (${{ matrix.os }}, Atom ${{ matrix.atom-channel }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        atom-channel: [stable]
    steps:
    - uses: actions/checkout@v2
    - uses: UziTech/action-setup-atom@v1
      with:
        channel: ${{ matrix.atom-channel }}
    - name: Atom version
      run: atom -v
    - name: APM version
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Run tests
      run: atom --test spec
