name: Test

on: [push, pull_request]

jobs:

  Specs:
    name: Atom Specs (${{ matrix.os }}, Atom ${{ matrix.atom-channel }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [14.x]
        atom-channel: [stable]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm version
      run: npm -v
    - name: Use Atom ${{ matrix.atom-channel }}
      uses: UziTech/action-setup-atom@v1
      with:
        channel: ${{ matrix.atom-channel }}
    - name: Atom version
      run: atom -v
    - name: APM version
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Build
      run: npm run build
    - name: Run tests
      run: atom --test spec
